Repository cms-patatrack/cmssw, pull requests merged in 2018-09, with the labels that each got.

#153 Improve CUDAService log messages
  HeterogeneousCore/CUDAServices/src/CUDAService.cc
  HeterogeneousCore/CUDAServices/test/testCUDAService.py
Labels: comparison-pending, core-pending, pending-signatures, tests-pending

#144 Add pixel tracking workflows for data
  Configuration/PyReleaseValidation/python/relval_standard.py
  Configuration/PyReleaseValidation/python/relval_steps.py
Labels: pdmv-pending, pending-signatures, tests-pending, upgrade-pending

#154 edm::Wrapper<> de/serialisation
  HeterogeneousCore/MPICore/BuildFile.xml
  HeterogeneousCore/MPICore/interface/WrapperHandle.h
  HeterogeneousCore/MPICore/interface/serialization.h
  HeterogeneousCore/MPICore/src/serialization.cc
Labels: comparison-pending, new-package-pending, pending-signatures, tests-pending

#159 Reduce CA memory need
  RecoPixelVertexing/PixelTriplets/plugins/CAHitQuadrupletGeneratorGPU.cu
  RecoPixelVertexing/PixelTriplets/plugins/CAHitQuadrupletGeneratorGPU.h
  RecoPixelVertexing/PixelTriplets/plugins/gpuPixelDoublets.h
Labels: comparison-pending, pending-signatures, reconstruction-pending, tests-pending

#156 Add MTV instance for pixel tracks from PV
  Validation/RecoTrack/python/PostProcessorTracker_cfi.py
  Validation/RecoTrack/python/TrackValidation_cff.py
  Validation/RecoTrack/python/plotting/html.py
  Validation/RecoTrack/python/plotting/trackingPlots.py
Labels: comparison-pending, dqm-pending, pending-signatures, tests-pending

#167 Optimise gpuPixelDoublets::doubletsFromHisto() kernel
  RecoPixelVertexing/PixelTriplets/plugins/CAHitQuadrupletGeneratorGPU.cu
  RecoPixelVertexing/PixelTriplets/plugins/gpuPixelDoublets.h
Labels: comparison-pending, pending-signatures, reconstruction-pending, tests-pending

#163 reducing number of maxHits in CA
  RecoLocalTracker/SiPixelClusterizer/interface/PixelTrackingGPUConstants.h
  RecoPixelVertexing/PixelTriplets/plugins/CAHitQuadrupletGeneratorGPU.cu
  RecoPixelVertexing/PixelTriplets/plugins/CAHitQuadrupletGeneratorGPU.h
Labels: comparison-pending, pending-signatures, reconstruction-pending, tests-pending

#174 Riemann fit multiple scattering
  RecoPixelVertexing/PixelTrackFitting/interface/RiemannFit.h
Labels: enhancement

#180 Work around atomicAdd problem on Volta
  RecoLocalTracker/SiPixelClusterizer/plugins/gpuClustering.h
  RecoPixelVertexing/PixelVertexFinding/src/gpuClusterTracks.h
Labels: bug

#179 fix mask in warp
  HeterogeneousCore/CUDAUtilities/interface/prefixScan.h
  HeterogeneousCore/CUDAUtilities/test/prefixScan_t.cu
Labels: bug
