Repository cms-patatrack/cmssw, pull requests merged in 2018-08, with the labels that each got.

#103 Extend the CUDAService to support CUDA device flags and limits
  HeterogeneousCore/CUDAServices/src/CUDAService.cc
Labels: enhancement

#124 Move CPU-CA internal headers back to src
  RecoPixelVertexing/PixelTriplets/plugins/CAHitQuadrupletGeneratorGPU.cc
  RecoPixelVertexing/PixelTriplets/src/CACell.h
  RecoPixelVertexing/PixelTriplets/src/CAGraph.h
  RecoPixelVertexing/PixelTriplets/src/CAHitQuadrupletGenerator.cc
  RecoPixelVertexing/PixelTriplets/src/CAHitTripletGenerator.cc
  RecoPixelVertexing/PixelTriplets/src/CellularAutomaton.cc
  RecoPixelVertexing/PixelTriplets/src/CellularAutomaton.h
Labels: enhancement

#126 Remove GPU-CA dependence on CPU doublets
  RecoPixelVertexing/PixelTrackFitting/python/PixelTracks_cff.py
  RecoPixelVertexing/PixelTriplets/plugins/CAHitNtupletHeterogeneousEDProducer.cc
Labels: enhancement

#127 Fix uninitialized memory access in GPU CellularAutomaton
  RecoPixelVertexing/PixelTriplets/plugins/CAHitQuadrupletGeneratorGPU.cu
Labels: bug

#141 Workaround for std::array::size()
  HeterogeneousCore/Product/interface/HeterogeneousProduct.h
Labels: comparison-pending, new-package-pending, pending-signatures, tests-pending

#143 clang-format RiemannFit.h
  RecoPixelVertexing/PixelTrackFitting/interface/RiemannFit.h
Labels: comparison-pending, pending-signatures, reconstruction-pending, tests-pending
