Repository cms-patatrack/cmssw, pull requests merged in 2018-07, with the labels that each got.

#88 Show acquire() calls in the profile
  HeterogeneousCore/CUDAServices/plugins/NVProfilerService.cc
Labels: comparison-pending, core-pending, pending-signatures, tests-pending

#110 Fix the NVProfilerService crash(es)
  HeterogeneousCore/CUDAServices/plugins/NVProfilerService.cc
  HeterogeneousCore/CUDAServices/src/CUDAService.cc
Labels: bug

#109 Remove all remaining calls to cudaStreamSynchronize()
  RecoLocalTracker/SiPixelClusterizer/plugins/BuildFile.xml
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterGPUKernel.cu
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterGPUKernel.h
  RecoLocalTracker/SiPixelClusterizer/plugins/siPixelRawToClusterHeterogeneousProduct.h
  RecoLocalTracker/SiPixelRecHits/plugins/PixelRecHits.cu
  RecoLocalTracker/SiPixelRecHits/plugins/PixelRecHits.h
  RecoLocalTracker/SiPixelRecHits/plugins/SiPixelRecHitHeterogeneous.cc
  RecoLocalTracker/SiPixelRecHits/plugins/siPixelRecHitsHeterogeneousProduct.h
Labels: enhancement
