Repository cms-patatrack/cmssw, pull requests merged in 2018-03, with the labels that each got.

#29 Remove -O2/-O3 from CUDA flags
  DataFormats/GeometrySurface/test/BuildFile.xml
  EventFilter/SiPixelRawToDigi/plugins/BuildFile.xml
  HeterogeneousCore/CUDAUtilities/test/BuildFile.xml
  RecoLocalTracker/SiPixelClusterizer/test/BuildFile.xml
  RecoLocalTracker/SiPixelRecHits/plugins/BuildFile.xml
Labels: comparison-pending, new-package-pending, pending-signatures, reconstruction-pending, simulation-pending, tests-pending

#23 Add a DQM sequence for pixel-only tracking
  Configuration/PyReleaseValidation/python/relval_steps.py
  DQM/TrackingMonitorClient/python/pixelTrackingEffFromHitPattern_cff.py
  DQM/TrackingMonitorSource/python/pixelTracksMonitoring_cff.py
  DQMOffline/Configuration/python/DQMOffline_SecondStep_cff.py
  DQMOffline/Configuration/python/DQMOffline_cff.py
  DQMOffline/Configuration/python/autoDQM.py
Labels: comparison-pending, dqm-pending, pdmv-pending, pending-signatures, tests-started, upgrade-pending

#30 Set siPixelClusters.payloadType=HLT
  RecoLocalTracker/SiPixelClusterizer/python/SiPixelClusterizer_cfi.py
Labels: comparison-pending, pending-signatures, reconstruction-pending, tests-pending

#18 GPU2CPU for clusters and RecHIts
  EventFilter/SiPixelRawToDigi/plugins/RawToDigiGPU.cu
  EventFilter/SiPixelRawToDigi/plugins/RawToDigiGPU.h
  EventFilter/SiPixelRawToDigi/plugins/SiPixelRawToDigiGPU.cc
  EventFilter/SiPixelRawToDigi/plugins/SiPixelRawToDigiGPU.h
  RecoLocalTracker/SiPixelRecHits/interface/PixelCPEFast.h
  RecoLocalTracker/SiPixelRecHits/interface/pixelCPEforGPU.h
  RecoLocalTracker/SiPixelRecHits/plugins/PixelRecHits.cu
  RecoLocalTracker/SiPixelRecHits/plugins/PixelRecHits.h
  RecoLocalTracker/SiPixelRecHits/plugins/SiPixelRecHitGPU.cc
  RecoLocalTracker/SiPixelRecHits/plugins/gpuPixelRecHits.h
  RecoLocalTracker/SiPixelRecHits/python/SiPixelRecHitsGPU_cfi.py
  RecoLocalTracker/SiPixelRecHits/src/PixelCPEFast.cc
Labels: comparison-pending, pending-signatures, reconstruction-pending, tests-pending

#32 speed up cluster copy (2CPU) by factor 2
  EventFilter/SiPixelRawToDigi/plugins/RawToDigiGPU.cu
  EventFilter/SiPixelRawToDigi/plugins/SiPixelRawToDigiGPU.cc
Labels: comparison-pending, pending-signatures, reconstruction-pending, tests-pending

#35 Use CUDA Unified Addressing, and implement a CUDA-aware allocator
  EventFilter/SiPixelRawToDigi/plugins/RawToDigiGPU.cu
  EventFilter/SiPixelRawToDigi/plugins/SiPixelFedCablingMapGPU.cc
  EventFilter/SiPixelRawToDigi/plugins/SiPixelFedCablingMapGPU.h
  EventFilter/SiPixelRawToDigi/plugins/SiPixelRawToDigiGPU.cc
  EventFilter/SiPixelRawToDigi/plugins/SiPixelRawToDigiGPU.h
  HeterogeneousCore/CUDAUtilities/interface/CUDAHostAllocator.h
  HeterogeneousCore/CUDAUtilities/test/test_GPUSimpleVector.cu
  RecoLocalTracker/SiPixelRecHits/interface/PixelCPEFast.h
  RecoLocalTracker/SiPixelRecHits/plugins/PixelRecHits.cu
  RecoLocalTracker/SiPixelRecHits/src/PixelCPEFast.cc
Labels: comparison-pending, new-package-pending, pending-signatures, reconstruction-pending, tests-pending

#34 Riemann fit patatrack
  RecoPixelVertexing/PixelTrackFitting/BuildFile.xml
  RecoPixelVertexing/PixelTrackFitting/interface/PixelFitterByRiemannParaboloid.h
  RecoPixelVertexing/PixelTrackFitting/interface/RiemannFit.h
  RecoPixelVertexing/PixelTrackFitting/plugins/PixelFitterByRiemannParaboloidProducer.cc
  RecoPixelVertexing/PixelTrackFitting/python/PixelTracks_cff.py
  RecoPixelVertexing/PixelTrackFitting/python/pixelFitterByRiemannParaboloid_cfi.py
  RecoPixelVertexing/PixelTrackFitting/src/PixelFitterByRiemannParaboloid.cc
  RecoPixelVertexing/PixelTrackFitting/src/PixelTrackBuilder.cc
  RecoPixelVertexing/PixelTrackFitting/test/BuildFile.xml
  RecoPixelVertexing/PixelTrackFitting/test/PixelTrackRiemannFit.cc
  RecoPixelVertexing/PixelTrackFitting/test/testEigenGPU.cu
  RecoPixelVertexing/PixelTrackFitting/test/testEigenGPUNoFit.cu
  RecoPixelVertexing/PixelTrackFitting/test/test_common.h
Labels: comparison-pending, pending-signatures, reconstruction-pending, tests-pending

#36 Replace std::cout with LogTrace
  RecoPixelVertexing/PixelTrackFitting/src/PixelTrackBuilder.cc
Labels: comparison-pending, pending-signatures, reconstruction-pending, tests-pending
