Repository cms-patatrack/cmssw, pull requests merged in 2018-05, with the labels that each got.

#43 Replace AcceleratorService with HeterogeneousEDProducer
  HeterogeneousCore/AcceleratorService/interface/AcceleratorService.h
  HeterogeneousCore/AcceleratorService/plugins/BuildFile.xml
  HeterogeneousCore/AcceleratorService/plugins/plugins.cc
  HeterogeneousCore/AcceleratorService/src/AcceleratorService.cc
  HeterogeneousCore/AcceleratorService/test/TestAcceleratorServiceProducerGPU.cc
  HeterogeneousCore/AcceleratorService/test/TestAcceleratorServiceProducerGPUHelpers.h
  HeterogeneousCore/AcceleratorService/test/TestAcceleratorServiceProducerGPUMock.cc
  HeterogeneousCore/CUDACore/BuildFile.xml
  HeterogeneousCore/CUDACore/interface/GPUCuda.h
  HeterogeneousCore/CUDACore/src/GPUCuda.cc
  HeterogeneousCore/CUDAServices/interface/CUDAService.h
  HeterogeneousCore/CUDAServices/src/CUDAService.cc
  HeterogeneousCore/CUDAServices/test/testCUDAService.cpp
  HeterogeneousCore/Producer/BuildFile.xml
  HeterogeneousCore/Producer/interface/DeviceWrapper.h
  HeterogeneousCore/Producer/interface/HeterogeneousEDProducer.h
  HeterogeneousCore/Producer/interface/HeterogeneousEvent.h
  HeterogeneousCore/Producer/src/HeterogeneousEDProducer.cc
  HeterogeneousCore/Producer/test/BuildFile.xml
  HeterogeneousCore/Producer/test/TestHeterogeneousEDProducerAnalyzer.cc
  HeterogeneousCore/Producer/test/TestHeterogeneousEDProducerGPU.cc
  HeterogeneousCore/Producer/test/TestHeterogeneousEDProducerGPUHelpers.cu
  HeterogeneousCore/Producer/test/TestHeterogeneousEDProducerGPUHelpers.h
  HeterogeneousCore/Producer/test/TestHeterogeneousEDProducerGPUMock.cc
  HeterogeneousCore/Producer/test/testGPUMock_cfg.py
  HeterogeneousCore/Producer/test/testGPU_cfg.py
  HeterogeneousCore/Product/interface/HeterogeneousDeviceId.h
  HeterogeneousCore/Product/interface/HeterogeneousProduct.h
  HeterogeneousCore/Product/interface/HeterogeneousProductBase.h
  HeterogeneousCore/Product/test/testHeterogeneousProduct.cpp
  HeterogeneousCore/README.md
Labels: comparison-pending, core-pending, new-package-pending, pending-signatures, tests-pending

#46 Move the partial_sum to the GPU
  RecoLocalTracker/SiPixelRecHits/plugins/PixelRecHits.cu
Labels: comparison-pending, pending-signatures, reconstruction-pending, tests-pending

#47 Remove the use of #pragma once
  CondFormats/SiPixelObjects/interface/SiPixelGainForHLTonGPU.h
  RecoLocalTracker/SiPixelClusterizer/plugins/gpuCalibPixel.h
  RecoLocalTracker/SiPixelClusterizer/plugins/gpuClustering.h
  RecoLocalTracker/SiPixelRecHits/interface/PixelCPEFast.h
  RecoLocalTracker/SiPixelRecHits/plugins/PixelRecHits.h
  RecoLocalTracker/SiPixelRecHits/plugins/gpuPixelRecHits.h
Labels: alca-pending, comparison-pending, db-pending, pending-signatures, reconstruction-pending, tests-pending

#50 Updates to HeterogeneousEDProducer
  HeterogeneousCore/CUDACore/interface/GPUCuda.h
  HeterogeneousCore/CUDACore/src/GPUCuda.cc
  HeterogeneousCore/Producer/README.md
  HeterogeneousCore/Producer/interface/HeterogeneousEDProducer.h
  HeterogeneousCore/Producer/interface/HeterogeneousEvent.h
  HeterogeneousCore/Producer/src/HeterogeneousEDProducer.cc
  HeterogeneousCore/Producer/test/TestHeterogeneousEDProducerGPU.cc
  HeterogeneousCore/Producer/test/TestHeterogeneousEDProducerGPUMock.cc
  HeterogeneousCore/Producer/test/testGPUMock_cfg.py
  HeterogeneousCore/Producer/test/testGPU_cfg.py
  HeterogeneousCore/Product/interface/HeterogeneousProduct.h
Labels: comparison-pending, new-package-pending, pending-signatures, tests-pending

#49 Clean up some GPU- and non-GPU-related pixel tracking code
  EventFilter/SiPixelRawToDigi/plugins/BuildFile.xml
  EventFilter/SiPixelRawToDigi/plugins/DetParamBits.h
  EventFilter/SiPixelRawToDigi/plugins/EventInfoGPU.h
  EventFilter/SiPixelRawToDigi/plugins/RawToDigiGPU.cu
  EventFilter/SiPixelRawToDigi/plugins/RawToDigiGPU.h
  EventFilter/SiPixelRawToDigi/plugins/SealModule.cc
  EventFilter/SiPixelRawToDigi/plugins/SiPixelDigiToRaw.cc
  EventFilter/SiPixelRawToDigi/plugins/SiPixelFedCablingMapGPU.cc
  EventFilter/SiPixelRawToDigi/plugins/SiPixelFedCablingMapGPU.h
  EventFilter/SiPixelRawToDigi/plugins/SiPixelRawToDigi.cc
  EventFilter/SiPixelRawToDigi/plugins/SiPixelRawToDigiGPU.cc
  EventFilter/SiPixelRawToDigi/plugins/SiPixelRawToDigiGPU.h
  EventFilter/SiPixelRawToDigi/plugins/SiPixelRawToDigiGPUKernel.cu
  EventFilter/SiPixelRawToDigi/plugins/SiPixelRawToDigiGPUKernel.h
  RecoLocalTracker/SiPixelRecHits/interface/pixelCPEforGPU.h
  RecoLocalTracker/SiPixelRecHits/plugins/PixelRecHits.cu
  RecoLocalTracker/SiPixelRecHits/plugins/PixelRecHits.h
  RecoLocalTracker/SiPixelRecHits/plugins/SiPixelRecHitGPU.cc
  RecoLocalTracker/SiPixelRecHits/plugins/gpuPixelRecHits.h
Labels: comparison-pending, pending-signatures, reconstruction-pending, tests-pending

#52 Generalize HeterogeneousEvent::getByToken() to support standard products
  HeterogeneousCore/Producer/interface/HeterogeneousEvent.h
  HeterogeneousCore/Producer/test/TestHeterogeneousEDProducerGPUMock.cc
  HeterogeneousCore/Producer/test/testGPUMock_cfg.py
Labels: comparison-pending, new-package-pending, pending-signatures, tests-pending

#54 Various updates to the heterogeneous framework
  Configuration/Applications/python/ConfigBuilder.py
  HeterogeneousCore/CUDACore/src/GPUCuda.cc
  HeterogeneousCore/Producer/interface/HeterogeneousEvent.h
  HeterogeneousCore/Producer/test/TestHeterogeneousEDProducerGPUMock.cc
Labels: comparison-pending, new-package-pending, operations-pending, pending-signatures, tests-pending

#55 [RFC] constexpr for DetId
  DataFormats/DetId/interface/DetId.h
  DataFormats/DetId/test/BuildFile.xml
  DataFormats/DetId/test/test_detid.cu
Labels: comparison-pending, pending-signatures, simulation-pending, tests-pending

#56 Add a copy constructor to edmNew::DetSetVector
  DataFormats/Common/interface/DetSetVectorNew.h
  DataFormats/Common/test/DetSetNew_t.cpp
Labels: comparison-pending, core-pending, pending-signatures, tests-pending

#61 Add heterogeneous framework documentation and add some sanity checks in GPUCuda
  HeterogeneousCore/CUDACore/src/GPUCuda.cc
  HeterogeneousCore/Producer/README.md
Labels: comparison-pending, new-package-pending, pending-signatures, tests-pending
