Repository cms-patatrack/cmssw, pull requests merged in 2019-03, with the labels that each got.

#284 bugfix - change treatment of GPU tracks not on CPU
  RecoPixelVertexing/PixelVertexFinding/src/PixelVertexHeterogeneousProducer.cc
Labels: bug-fix

#294 make gpu-cpu cluster matching deterministic
  DataFormats/SiPixelCluster/interface/SiPixelCluster.h
  DataFormats/SiPixelCluster/src/classes_def.xml
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelDigisClustersFromSoA.cc
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterCUDA.cc
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterGPUKernel.cu
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterGPUKernel.h
  RecoLocalTracker/SiPixelRecHits/plugins/SiPixelRecHitHeterogeneous.cc
Labels: Pixels

#302 Silence nvcc warnings
  HeterogeneousCore/CUDAUtilities/test/BuildFile.xml
  HeterogeneousCore/CUDAUtilities/test/radixSort_t.cu
Labels: fixed
