Repository cms-patatrack/cmssw, pull requests merged in 2019-04, with the labels that each got.

#321 Fix number of floats per hit
  RecoPixelVertexing/PixelTrackFitting/plugins/PixelTrackReconstructionGPU.cc
  RecoPixelVertexing/PixelTrackFitting/plugins/PixelTrackReconstructionGPU.cu
Labels: Pixels

#320 Fix the CUDA product availability logic in rechit
  RecoLocalTracker/SiPixelRecHits/plugins/SiPixelRecHitHeterogeneous.cc
Labels: Pixels, bug-fix

#318 Move BeamSpot transfer to GPU to its own producer
  CUDADataFormats/BeamSpot/BuildFile.xml
  CUDADataFormats/BeamSpot/interface/BeamSpotCUDA.h
  CUDADataFormats/BeamSpot/src/BeamSpotCUDA.cc
  CUDADataFormats/BeamSpot/src/classes.h
  CUDADataFormats/BeamSpot/src/classes_def.xml
  CUDADataFormats/Common/interface/CUDAProduct.h
  Configuration/StandardSequences/python/Reconstruction_cff.py
  HeterogeneousCore/CUDAUtilities/BuildFile.xml
  HeterogeneousCore/CUDAUtilities/interface/host_noncached_unique_ptr.h
  HeterogeneousCore/CUDAUtilities/test/BuildFile.xml
  HeterogeneousCore/CUDAUtilities/test/host_noncached_unique_ptr_t.cpp
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterCUDA.cc
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterGPUKernel.cu
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterGPUKernel.h
  RecoLocalTracker/SiPixelRecHits/plugins/BuildFile.xml
  RecoLocalTracker/SiPixelRecHits/plugins/PixelRecHits.cu
  RecoLocalTracker/SiPixelRecHits/plugins/PixelRecHits.h
  RecoLocalTracker/SiPixelRecHits/plugins/SiPixelRecHitHeterogeneous.cc
  RecoLocalTracker/SiPixelRecHits/plugins/gpuPixelRecHits.h
  RecoLocalTracker/SiPixelRecHits/plugins/siPixelRecHitsHeterogeneousProduct.h
  RecoVertex/BeamSpotProducer/plugins/BeamSpotToCUDA.cc
  RecoVertex/BeamSpotProducer/plugins/BuildFile.xml
  RecoVertex/BeamSpotProducer/python/BeamSpot_cff.py
Labels: Beam spot

#301 Simplify SiPixelFedCablingMapGPU SoA
  RecoLocalTracker/SiPixelClusterizer/interface/SiPixelFedCablingMapGPU.h
  RecoLocalTracker/SiPixelClusterizer/interface/SiPixelFedCablingMapGPUWrapper.h
  RecoLocalTracker/SiPixelClusterizer/src/SiPixelFedCablingMapGPUWrapper.cc
Labels: Pixels
