Repository cms-patatrack/cmssw, pull requests merged in 2020-10, with the labels that each got.

#551 Fix BS naming in siPixelRecHitsCUDAPreSplitting
  RecoLocalTracker/SiPixelRecHits/python/SiPixelRecHits_cfi.py
Labels: bug-fix

#553 Add customisations for profiling the Pixel-only workflow
  RecoTracker/Configuration/python/customizePixelOnlyForProfiling.py
Labels: Pixels

#556 Further clean up after merging CMSSW_11_2_0_pre7
  CUDADataFormats/Common/interface/ArrayShadow.h
  CUDADataFormats/Track/src/classes.h
  CUDADataFormats/Track/src/classes_def.xml
  EventFilter/EcalRawToDigi/plugins/BuildFile.xml
  RecoPixelVertexing/Configuration/python/customizePixelTracksForProfiling.py
Labels: fixed, task

#549 Updating RelVal WF & customisation on CPU
  Configuration/PyReleaseValidation/python/relval_2017.py
  Configuration/PyReleaseValidation/python/relval_steps.py
  Configuration/PyReleaseValidation/python/upgradeWorkflowComponents.py
  RecoPixelVertexing/Configuration/python/customizePixelTracksSoAonCPU.py
Labels: Pixels, enhancement

#557 Move multifit/MAHI common code to DataFormats/CaloRecHit
  CondFormats/HcalObjects/interface/HcalCondObjectContainer.h
  DataFormats/CaloRecHit/interface/MultifitComputations.h
  RecoLocalCalo/EcalRecProducers/plugins/AmplitudeComputationKernels.cu
  RecoLocalCalo/EcalRecProducers/plugins/KernelHelpers.h
  RecoLocalCalo/HcalRecProducers/src/KernelHelpers.h
  RecoLocalCalo/HcalRecProducers/src/MahiGPU.cu
Labels: HCAL

#560 Move the siPixelClusters.payloadType change to the SoA-on-CPU customisation
  RecoLocalTracker/SiPixelClusterizer/python/SiPixelClusterizer_cfi.py
  RecoPixelVertexing/Configuration/python/customizePixelTracksSoAonCPU.py
Labels: Pixels
