Repository cms-patatrack/cmssw, pull requests merged in 2020-07, with the labels that each got.

#492 fix gain&pede for run3
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterCUDA.cc
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterGPUKernel.cu
  RecoLocalTracker/SiPixelClusterizer/plugins/SiPixelRawToClusterGPUKernel.h
  RecoLocalTracker/SiPixelClusterizer/plugins/gpuCalibPixel.h
  RecoLocalTracker/SiPixelClusterizer/python/siPixelClustersPreSplitting_cff.py
Labels: Pixels, bug-fix

#499 fix max track size in vertex soa
  CUDADataFormats/Vertex/interface/ZVertexSoA.h
Labels: Pixels, bug-fix, fixed

#505 Implement HCAL-only workflows on GPU
  RecoLocalCalo/Configuration/python/customizeHcalOnlyForProfiling.py
  RecoLocalCalo/Configuration/python/hcalLocalReco_cff.py
  RecoLocalCalo/HcalRecProducers/python/hbheRecHitProducerGPUTask_cff.py
Labels: HCAL

#511 Migrate EcalUncalibRecHitProducerGPU to use ESGetToken's
  RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitProducerGPU.cc
Labels: ECAL

#517 Set max channels separately EE and EB for ECAL
  EventFilter/EcalRawToDigi/plugins/DeclsForKernels.h
  EventFilter/EcalRawToDigi/plugins/EcalCPUDigisProducer.cc
  EventFilter/EcalRawToDigi/plugins/EcalRawToDigiGPU.cc
  HLTrigger/Configuration/python/customizeHLTforPatatrack.py
  RecoLocalCalo/EcalRecProducers/plugins/DeclsForKernels.h
  RecoLocalCalo/EcalRecProducers/plugins/EcalRecHitProducerGPU.cc
  RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitProducerGPU.cc
  RecoLocalCalo/EcalRecProducers/python/ecalRecHitGPU_cfi.py
Labels: ECAL, bug-fix

#524 Code format on top of master 11.1
  EventFilter/EcalRawToDigi/plugins/DeclsForKernels.h
  RecoLocalCalo/EcalRecProducers/plugins/DeclsForKernels.h
  RecoLocalCalo/EcalRecProducers/plugins/EcalRecHitProducerGPU.cc
  RecoLocalCalo/EcalRecProducers/plugins/EcalUncalibRecHitProducerGPU.cc
Labels: bug-fix

#523 ECAL-HCAL: code refactoring
  DataFormats/Math/interface/EigenComputations.h
  RecoLocalCalo/EcalRecProducers/plugins/AmplitudeComputationKernels.cu
  RecoLocalCalo/EcalRecProducers/plugins/KernelHelpers.h
  RecoLocalCalo/HcalRecProducers/src/KernelHelpers.h
  RecoLocalCalo/HcalRecProducers/src/MahiGPU.cu
  RecoLocalCalo/HcalRecProducers/src/MahiGPU.h
Labels: ECAL, HCAL

#506 Improve CUDAMonitoringService
  HeterogeneousCore/CUDAServices/plugins/CUDAMonitoringService.cc
  HeterogeneousCore/CUDAUtilities/interface/deviceAllocatorStatus.h
  HeterogeneousCore/CUDAUtilities/src/CachingDeviceAllocator.h
  HeterogeneousCore/CUDAUtilities/src/deviceAllocatorStatus.cc
Labels: enhancement

#525 Remove duplicate definition of globalValidationHCALOnly
  Validation/Configuration/python/globalValidation_cff.py
Labels: HCAL
